### ISSUE TITLE
trial issue

### ISSUE THREAD

**Issue by shranuu** [shranuu/forforking#6]
# try commenting, resolving and closing the issue
just creating a trial issue to see how it works;
dont know how to link files to the issue; 

[Discussion_day2_evening.txt](https://github.com/user-attachments/files/17928878/Discussion_day2_evening.txt)

@shranuu 

referencing: #1

**Comment by SwathiS02** [comment]
abcdefgh

**Comment by shranuu** [comment]
i can see your comment :)
